jester_table = {
    ["j_joker"] = {},
    ["j_greedy_joker"] = {},
    ["j_lusty_joker"] = {},
    ["j_wrathful_joker"] = {},
    ["j_gluttenous_joker"] = {},
    ["j_jolly"] = {},
    ["j_zany"] = {},
    ["j_mad"] = {},
    ["j_crazy"] = {},
    ["j_droll"] = {},
    ["j_sly"] = {},
    ["j_wily"] = {},
    ["j_clever"] = {},
    ["j_devious"] = {},
    ["j_crafty"] = {},
    ["j_half"] = {},
    ["j_stencil"] = {},
    ["j_four_fingers"] = {"handy"},
    ["j_mime"] = {"bellist"},
    ["j_credit_card"] = {},
    ["j_ceremonial"] = {"lives"},
    ["j_banner"] = {},
    ["j_mystic_summit"] = {"stone"},
    ["j_marble"] = {"stone", "dam_builder"},
    ["j_loyalty_card"] = {},
    ["j_8_ball"] = {}, -- Add Hoarder
    ["j_misprint"] = {"amorphous"},
    ["j_dusk"] = {},
    ["j_raised_fist"] = {},
    ["j_chaos"] = {},
    ["j_fibonacci"] = {},
    ["j_steel_joker"] = {},
    ["j_scary_face"] = {},
    ["j_abstract"] = {},
    ["j_delayed_grat"] = {},
    ["j_hack"] = {},
    ["j_pareidolia"] = {},
    ["j_gros_michel"] = {"morsel"},
    ["j_even_steven"] = {},
    ["j_odd_todd"] = {},
    ["j_scholar"] = {},
    ["j_business"] = {},
    ["j_supernova"] = {},
    ["j_ride_the_bus"] = {},
    ["j_space"] = {},
    ["j_egg"] = {"morsel", "parasite"},
    ["j_burglar"] = {"handy"},
    ["j_blackboard"] = {},
    ["j_runner"] = {}, -- Add Sprinter
    ["j_ice_cream"] = {"frozen","morsel"},
    ["j_dna"] = {"fecundity"},
    ["j_splash"] = {"waterborne"},
    ["j_blue_joker"] = {},
    ["j_sixth_sense"] = {}, -- Add Hoarder
    ["j_constellation"] = {"tidal"},
    ["j_hiker"] = {"fledgling"},
    ["j_faceless"] = {},
    ["j_green_joker"] = {},
    ["j_superposition"] = {},
    ["j_todo_list"] = {},
    ["j_cavendish"] = {"morsel","double"},
    ["j_card_sharp"] = {},
    ["j_red_card"] = {},
    ["j_madness"] = {"touch_death"}, -- Add Blood Lust
    ["j_square"] = {},
    ["j_seance"] = {}, -- Add Hoarder
    ["j_riff_raff"] = {"gifter"},
    ["j_vampire"] = {}, -- Add Blood Lust
    ["j_shortcut"] = {},
    ["j_hologram"] = {}, -- Add Vessel Printer
    ["j_vagabond"] = {}, -- Add Hoarder
    ["j_baron"] = {"leader"}, 
    ["j_cloud_9"] = {"airborne"},
    ["j_rocket"] = {"airborne"},
    ["j_obelisk"] = {"stone","repulsive"},
    ["j_midas_mask"] = {},
    ["j_luchador"] = {"guardian"},
    ["j_photograph"] = {},
    ["j_gift"] = {},
    ["j_turtle_bean"] = {"morsel"},
    ["j_erosion"] = {"stone","waterborne"},
    ["j_reserved_parking"] = {},
    ["j_mail"] = {},
    ["j_to_the_moon"] = {},
    ["j_hallucination"] = {"trinket"},
    ["j_fortune_teller"] = {}, -- Add Mental Gymnastics
    ["j_juggler"] = {},
    ["j_drunkard"] = {},
    ["j_stone"] = {"stone"},
    ["j_golden"] = {},
    ["j_lucky_cat"] = {"lives"},
    ["j_baseball"] = {},
    ["j_bull"] = {}, -- Add Rampager
    ["j_diet_cola"] = {"morsel","waterborne"},
    ["j_trading"] = {},
    ["j_flash"] = {},
    ["j_popcorn"] = {"morsel"},
    ["j_trousers"] = {},
    ["j_ancient"] = {"stone"}, -- Add Ruby Heart
    ["j_ramen"] = {"morsel","waterborne"},
    ["j_walkie_talkie"] = {},
    ["j_selzer"] = {"morsel","waterborne"},
    ["j_castle"] = {},
    ["j_smiley"] = {},
    ["j_campfire"] = {},
    ["j_ticket"] = {},
    ["j_mr_bones"] = {"unkillable","bone_king"},
    ["j_acrobat"] = {},
    ["j_sock_and_buskin"] = {},
    ["j_swashbuckler"] = {},
    ["j_troubadour"] = {},
    ["j_certificate"] = {},
    ["j_smeared"] = {"amorphous"},
    ["j_throwback"] = {},
    ["j_hanging_chad"] = {"double"},
    ["j_rough_gem"] = {"stone"}, -- Add Orange Mox
    ["j_bloodstone"] = {"stone"}, -- Add Green Mox
    ["j_arrowhead"] = {"stone"}, -- Add Great Mox
    ["j_onyx_agate"] = {"stone"}, -- Add Blue Mox
    ["j_glass"] = {"overclocked"}, -- Add Brittle
    ["j_ring_master"] = {"gifter","trinket"},
    ["j_flower_pot"] = {},
    ["j_blueprint"] = {"amorphous","bellist"},
    ["j_wee"] = {},
    ["j_merry_andy"] = {},
    ["j_oops"] = {},
    ["j_idol"] = {"leader"},
    ["j_seeing_double"] = {},
    ["j_matador"] = {"mighty_leap","guardian"},
    ["j_hit_the_road"] = {},
    ["j_duo"] = {"bifurcated"},
    ["j_trio"] = {"trifurcated"},
    ["j_family"] = {"double","bifurcated"},
    ["j_order"] = {"bifurcated"}, -- Add Omni Strike
    ["j_tribe"] = {"double"}, -- Add Omni Strike
    ["j_stuntman"] = {},
    ["j_invisible"] = {"amorphous","fledgling"},
    ["j_brainstorm"] = {"amorphous","bellist"},
    ["j_satellite"] = {},
    ["j_shoot_the_moon"] = {},
    ["j_drivers_license"] = {},
    ["j_cartomancer"] = {}, -- Add Looter
    ["j_astronomer"] = {},
    ["j_burnt"] = {},
    ["j_bootstraps"] = {},
    ["j_caino"] = {"overclocked"}, -- Add Blood Lust
    ["j_triboulet"] = {"bellist", "leader"},
    ["j_yorick"] = {"lives","unkillable"},
    ["j_chicot"] = {"repulsive"}, -- Add Stinky
    ["j_perkeo"] = {"tidal"}, -- Add Corpse Eater
}
for k, joker in pairs(G.P_CENTER_POOLS['Joker']) do
    if joker.set == 'Joker' then 
        for key, _ in pairs(jester_table) do
            if key == joker.key then
                joker.config.insc_sacrifice_sigils = jester_table[joker.key]
                print(jester_table[joker.key])
            end
        end 
    end
end